### ISSUE TITLE
HomePage - Android

### ISSUE THREAD

**Issue by Harsh-2420** [Lakshya2610/Findr#10]
Push the HomePage Logo on closer to the top on Android and increase card size to be closer to filters and logo

![Screenshot 2020-06-09 at 2 03 11 PM](https://user-images.githubusercontent.com/50898873/84183528-096ae380-aa5a-11ea-8edf-ef8d83709239.png)

**Comment by Lakshya2610** [comment]
![image](https://user-images.githubusercontent.com/46510358/84184123-de34c400-aa5a-11ea-9b02-655e45f37672.png)
This is how it look on Android right now. (This screenshot is from a OnePlus 6)
