### ISSUE TITLE
Sign Up + Log In Logo

### ISSUE THREAD

**Issue by Harsh-2420** [Lakshya2610/Findr#11]
Fix the logo on the sign up and log in page

![Screenshot 2020-06-09 at 2 06 10 PM](https://user-images.githubusercontent.com/50898873/84183838-7a120000-aa5a-11ea-8a8d-e242cbeefcf5.png)

**Comment by Lakshya2610** [comment]
I fixed all the CSS bugs, but the dropdown that I added for Unis is a bit buggy. @gautamgireesh @parshvas25 @IbrahimFazili Can any one of you look at it and fix it. The branch is called [signup-login-bugfixes](https://github.com/Lakshya2610/Findr/tree/signup-login-bugfixes)

**Comment by IbrahimFazili** [comment]
@Lakshya2610 @gautamgireesh @Harsh-2420 isn't this issue resolved?
