### ISSUE TITLE
Match Swiping

### ISSUE THREAD

**Issue by IbrahimFazili** [Lakshya2610/Findr#118]
He knows whats the issue

**Comment by gautamgireesh** [comment]
Mashallah comment ebra @IbrahimFazili

**Comment by Harsh-2420** [comment]
Noice

**Comment by Lakshya2610** [comment]
When I see my homies create issues with comments like these
![image](https://user-images.githubusercontent.com/46510358/88489941-cdd29d00-cf65-11ea-84fa-c7b60e020e29.png)
