### ISSUE TITLE
Add local caching for Images to avoid multiple downloads for the same image in different parts of app

### ISSUE THREAD

**Issue by Lakshya2610** [Lakshya2610/Findr#29]
Currently, every page in the app requests the server for an image URL and downloads it again & again. This should only be done once. Caching the image locally would reduce server load and AWS costs for data usage

**Comment by Lakshya2610** [comment]
Since all images are loaded using pre-signed URLs that change every time, we might have to build a new caching system (or a React component) that caches images based on emails

**Comment by gautamgireesh** [comment]
@Lakshya2610 Isn't this issue solved?

**Comment by Lakshya2610** [comment]
Yeah, PR isn't merged yet though
