### ISSUE TITLE
Dropdown for signup needs work(Picking University)

### ISSUE THREAD

**Issue by gautamgireesh** [Lakshya2610/Findr#30]
Re-implement dropdown menu for signup page to match the rest of the page. Might have to use [this](https://www.npmjs.com/package/react-native-material-dropdown).

**Comment by IbrahimFazili** [comment]
@gautamgireesh can you take a look at the changes I made

**Comment by gautamgireesh** [comment]
@IbrahimFazili sure, i'll look at it.

**Comment by gautamgireesh** [comment]
@IbrahimFazili Looks good, just a few minor changes.

1. Make the dropdown field look closer to the date of birth field, add a rounded white border etc. And the word "University" text color white.
![WhatsApp Image 2020-06-22 at 3 05 00 PM](https://user-images.githubusercontent.com/46042207/85325733-1f38c980-b49a-11ea-9d28-f3c948d4277c.jpeg)

2. Round the edges of the actual dropdown.

3. First page, there's an -----OR----- photo on the drive, place that above the log in button.

**Comment by IbrahimFazili** [comment]
Check PR, this should be completed now

**Comment by gautamgireesh** [comment]
--OR-- photo above login remaining.

**Comment by IbrahimFazili** [comment]
--OR-- photo added

**Comment by IbrahimFazili** [comment]
@gautamgireesh this is done now no?

**Comment by Lakshya2610** [comment]
@gautamgireesh @IbrahimFazili What's the status of this? If this is done, please close the issue
